services:
  nestjs-task-manager-api:
    image: nestjs-task-manager-api
    container_name: nestjs-task-manager-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - "3000:3000"
    networks:
      - nestjs-task-manager-network

  db:
    image: postgres:16
    container_name: nestjs-task-manager-postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: nestjs_tasks_db
      POSTGRES_USER: maxim
      POSTGRES_PASSWORD: 1234
      TZ: "UTC"
    ports:
      - "25432:5432"
    networks:
      - nestjs-task-manager-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - nestjs-task-manager-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "18080:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: 12345678
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: "False"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "False"
    networks:
      - nestjs-task-manager-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  nestjs-task-manager-network:
    driver: bridge
